version: '3'
services:
  # React App Service
  react-app:
    image: akamustafa/voiture-front:1.0
    ports:
      - "3000:80"

  # Spring Boot App Service
  spring-app:
    image: voiture-back
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

  # MySQL Service
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voituredb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network: